version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2024.02.2
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "${ADMIN_PORT}:80/tcp"
    environment:
      TZ: 'Asia/Bangkok'
      WEBPASSWORD: ${WEB_PASSWORD}
    volumes:
      - ${PIHOLE_PATH}:/etc/pihole
      - ${DNSMASQ_PATH}:/etc/dnsmasq.d
    restart: always
